# Generated by Django 4.2.3 on 2023-07-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75, verbose_name="Titulo")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "slug",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="URL_amigable"
                    ),
                ),
                ("visible", models.BooleanField(verbose_name="Publicado?")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={"verbose_name": "Pagina", "verbose_name_plural": "Paginas",},
        ),
    ]
